INCLUDE ALLMACROS.INC
.MODEL LARGE
.STACK 64
.DATA 
MESS1 DB "*To start chatting press F2$"
MESS2 DB "*To start Galaxy War game press F3$"
MESS3 DB "*To end the program press ESC$" 
MESS4 DB "Enter your name: $"
MESS5 DB "WAITING FOR OTHER PLAYER$"
MESS6 DB "GAME IS PAUSED, PRESS ENTER TO CONTINUE$" 
MESS7 DB " WINSSSS!!!!! $"
MESS8 DB " WINSSSS!!!!! $"
MESS9 DB "                                       $" 
MESS10 DB 80D DUP (0DCH),"$"
MESS11 DB 80D DUP (0DBH),"$"
MESS12 DB ": $"   
MESS13 DB "PRESS F2 TO ACCEPT CHAT INVITATION$"
MESS14 DB "PRESS F3 TO ACCEPT GAME INVITATION$"    
INVITATION  DB ?
PSHAPE DB 0DBH
P1NAME DB 15 DUP("$") 
P2NAME DB 15 DUP("$")
BORDER DB 80 DUP("-"),"$" 
CLEARR DB  DUP(00H),"$"
P1POS DW 1226H
P2POS DW 0326H 
P1HEALTH DB 20D
P2HEALTH DB 20D
P1BPOS DW 5 DUP (0FFFFH)
P2BPOS DW 5 DUP (0FFFFH) 
HLTA DB "THE APP IS HALTED$"
P1COUNT DB 00H
P2COUNT DB 00H
PU1     DB 00H
PU2     DB 00H 
HEALTH  DB 20D DUP (03), "$"                                        
APPMODE DB ?
DIRECTION DB "L"
COUNTERHELPER DB 00H
COUNTER DB 00H 
NPUTIME DB 04H
PU1CLEARER DB 00H
PU2CLEARER DB 00H 
PUGEN DB 03,02,01,03,02,01,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03
PUIND DB 00H  
PUPOS DW 00H
P1WAVEPOS DW 1200H
P2WAVEPOS DW 0600H    
VALUE DB ?,"$"  
CURSORPOS1 DW 0000H
CURSORPOS2 DW 0D00H 
CHATCURSORSEN DW ?
CHATCURSORREC DW ? 
BEGINCHATSEN DW ?
BEGINCHATREC DW ?
CHATINVITATION DB 0 
RP1COUNT    DB  00H
RP1BARR     DW  5 DUP (?)
RP2COUNT    DB  00H
RP2BARR     DW  5 DUP (?)
TESTARRAY   DB  '0', '0','0$'
TIMERDELAY  DD  0FFFFFFFFH
 BARRIERLOCATION DW 0B00H
BARRIERRIGHT   DB  01H
BARRIERLEFT    DB  00H 
HOST DB 0 
DELAYER DW 0000H 
DELAYER1 DB 00H 
.CODE
MAIN PROC 
  MOV AX,@DATA ;MOV ADDRESS OF DATA LOACATION TO AX
  MOV DS,AX    ;MOV ADDRESS OF DATA LOCATION TO DS THROUGH AX



     CALL INTIALIZEAPP 
     
     
     
     
     
     MAINMENU:
     
     
     CALL MAINSC
    
     CMP APPMODE,0
     JZ CHAT    
     
     CMP APPMODE,1
     JZ GAME
     
     CMP APPMODE,2
     JZ HALT





























;--------------------------------------------GAME---------------------

     GAME:
     CALL INTIALIZEGAME 
     
     
     CALL INTIALIZESERIAL
     JMP MOVEPLAYERS    
     PAUSE:
	 CLEARBUFFER          
	 SETCURSOR 0B18H     
     SHOWMESSAGE MESS6  
	 MOV AH, 0H         
	 INT 16H            
	 CMP AH, 1CH         
	 JZ CLEARENTER        
     JMP PAUSE  
     
           
     MOVEPLAYERS: 
     
        MOV VALUE,0
       
        MOV DX,3FDH 		   ;Line Status Register  	
        IN AL,DX 			   ;Read Line Status
        TEST AL , 1
        JZ KAMEL 
        MOV DX,03F8H
        IN AL,DX
        MOV VALUE,AL
        
     CMP VALUE,48H          
     JZ FIRE2          
     CMP VALUE,4DH            
     JZ MOVEP2RIGHT      
     CMP VALUE,4BH          
     JZ MOVEP2LEFT      
     
    
     
              
         
                   
     CMP VALUE, 1CH        
     JZ PAUSE              
                   
                    
        KAMEL: 
     
     
     
     JMP POWERSETTER
     MP1:       
     CMP P1HEALTH,0
     JZ PLAYER2WINS
     CMP P2HEALTH,0
     JZ PLAYER1WINS  
     
     MOV AH,1H           
     INT 16H 
     
         
     CMP AH, 4DH        
     JZ MOVEP1RIGHT      
     CMP AH, 4BH         
     JZ MOVEP1LEFT
     CMP AH,48H 
     JZ FIRE1            
           
     
     
                 
     
 
      
     
   
             
                   
                   
      
        ;CMP AH,1H
        ;JZ REC1
      ;  MOV VALUE,AL
       ; CALL INTIALIZESERIAL
;
;        
;        CLEARBUFFER  
;        MOV BX,0 
;        SETCURSOR CHATCURSORSEN
;        MOV DX,CHATCURSORSEN 
;        CMP DL,4EH
;        JLE SKPTOP1 
;        mov ah, 06h
;        mov al, 0
;        mov bh, 07      
;        mov cx, BEGINCHATSEN
;        mov dx, 174Fh 
;        int 10h  
;        MOV DX,BEGINCHATSEN
;        MOV CHATCURSORSEN,DX
;        MOV BX,0 
;        SETCURSOR CHATCURSORSEN
;        SKPTOP1:
;        DISPLAYCHARACTER VALUE 
;        ADD CHATCURSORSEN,0001H
;        CLEARBUFFER 
;        MOV DX,3FDH	        ; Line Status Register
;        AGAIN1:  	
;        IN AL,DX 			;Read Line Status
;        AND al , 00100000b
;        JZ REC1
;        MOV DX,3F8H  		; Transmit data register
;        MOV AL,VALUE
;        OUT DX,AL   
;        REC1:
;        MOV DX,3FDH 		; Line Status Register  	
;        IN AL,DX 			;Read Line Status
;        AND AL , 1
;        JZ RETURN
;        MOV DX,03F8H
;        IN AL,DX 
;        MOV VALUE,AL
;        MOV BX,0
;        SETCURSOR CHATCURSORREC
;        MOV DX,CHATCURSORREC 
;        CMP DX,184EH
;        JLE SKP9  
;        mov ah, 06h
;        mov al, 0
;        mov bh, 07      
;        mov cx, BEGINCHATREC
;        mov dx, 184Fh 
;        int 10h 
;        MOV DX,BEGINCHATREC
;        MOV CHATCURSORREC,DX              
;        SETCURSOR CHATCURSORREC
;        SKP9:  
;        DISPLAYCHARACTER VALUE
;        ADD CHATCURSORREC,0001H
;RETURN:

     CMP AH,01
     JNZ CLEARA  
       
       MP2:
         
     JMP UPDATEBULLETS   
      
;----------------------------------------LEFT RIGHT MOVEMENTS OF PLAYER2------ 


     MOVEP2RIGHT:
     


     
     CLEARBUFFER  
     CMP PU1,1H
     JZ MOVEPLAYERS       
     CMP PU1, 2H
     JNZ NORMALP2RIGHT
     CMP P2POS, 0300H 
     JZ MOVEPLAYERS     
     MOV DIRECTION,"L"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS   
     
     
     NORMALP2RIGHT:
     CMP P2POS, 034BH    
     JZ MOVEPLAYERS     
     MOV DIRECTION,"R"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS 
     
     
     MOVEP2LEFT:
     


     
     CLEARBUFFER
     CMP PU1,1H
     JZ MOVEPLAYERS         
     CMP PU1, 2H
     JNZ NORMALP2LEFT
     CMP P2POS, 034BH   
     JZ MOVEPLAYERS      
      MOV DIRECTION,"R"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS 
     NORMALP2LEFT:
     CMP P2POS, 0300H    
     JZ MOVEPLAYERS      
     MOV DIRECTION,"L"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS   
     
        
;----------------------------------------LEFT RIGHT MOVEMENTS OF PLAYER1------     
   
   
     MOVEP1RIGHT: 
     
     
        MOV DX,3FDH
        SENDER3:	   	
        IN AL,DX 			   ;Read Line Status
        TEST al , 00100000b
        JZ SENDER3
        MOV DX,3F8H                 ; Transmit data register	  
        MOV AL,AH
        OUT DX,AL


     CLEARBUFFER 
     CMP PU2,1H
     JZ MOVEPLAYERS       
     CMP PU2, 2H
     JNZ NORMALP1RIGHT 
     CMP P1POS,1200H     
     JZ MOVEPLAYERS     
      MOV DIRECTION,"L"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     NORMALP1RIGHT:
     CMP P1POS,124BH     
     JZ MOVEPLAYERS      
      MOV DIRECTION,"R"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     MOVEP1LEFT:  
     
        MOV DX,3FDH
        SENDER4:	   	
        IN AL,DX 			   ;Read Line Status
        TEST al , 00100000b
        JZ SENDER4
        MOV DX,3F8H                 ; Transmit data register	  
        MOV AL,AH
        OUT DX,AL

     
     CLEARBUFFER 
     CMP PU2,1H
     JZ MOVEPLAYERS       
     CMP PU2, 2H
     JNZ NORMALP1LEFT
     CMP P1POS,124BH     
     JZ MOVEPLAYERS      
     MOV DIRECTION,"R"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     NORMALP1LEFT:
     CMP P1POS,1200H     
     JZ MOVEPLAYERS      
     MOV DIRECTION,"L"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
;------------------------------------------------FIRING------------------------     
     FIRE1:  
             
    
        MOV DX,3FDH
        SENDER5:	   	
        IN AL,DX 			   ;Read Line Status
        TEST al , 00100000b
        JZ SENDER5
        MOV DX,3F8H                 ; Transmit data register	  
        MOV AL,AH
        OUT DX,AL

         
     CLEARBUFFER
     CALL DRAWBULLETONE
      
                  
     JMP MOVEPLAYERS              
     FIRE2: 
    


     CLEARBUFFER        
     CALL DRAWBULLETTWO 
                     
     JMP MOVEPLAYERS             
;--------------------------------UPADTE BULLETS---------------------------------

     UPDATEBULLETS: 
     INC DELAYER 
     CMP DELAYER,04FFH  
     JNZ MOVEPLAYERS
     
     INC COUNTERHELPER
     MOV DELAYER,0000H
     CMP COUNTERHELPER,05FH 
     JNZ SKIPTOUPDATE
     MOV COUNTERHELPER,00
     INC COUNTER
     
     SKIPTOUPDATE:
     
    
      

   

     CALL DRAWBARRIERS
     CALL MOVEBARRIERS
     
     INC DELAYER1
     CMP DELAYER1,04H
     JNZ MOVEPLAYERS
     MOV DELAYER1,00H
     CALL REBOUNDBULLETONE
     CALL REBOUNDBULLETTWO 
     CALL UPDATEBULLETONE 
     CALL UPDATEBULLETTWO 
    
     
     JMP MOVEPLAYERS   
     
     CLEARA:           
     
     CLEARBUFFER       
     JMP MOVEPLAYERS   
     CLEARENTER:
     SETCURSOR 0B18H     
     SHOWMESSAGE MESS9 
     JMP MP2 
     PLAYER1WINS: 
     CLEARSCREEN
     SETCURSOR 0C1CH 
     SHOWMESSAGE P1NAME
     SHOWMESSAGE MESS7
     GETKEY
     JMP PLAYER1WINS
     PLAYER2WINS:  
     CLEARSCREEN
     
     SETCURSOR 0C1CH
     SHOWMESSAGE P2NAME
     SHOWMESSAGE MESS8 
     GETKEY
     JMP PLAYER2WINS 
     
     
     
     
     POWERSETTER: 
     MOV BL,COUNTER
     CMP PU1CLEARER,BL
     JNZ SKP1 
     MOV PU1,0
     SKP1: 
     CMP PU2CLEARER,BL
     JNZ SKP2 
     MOV PU2,0
     SKP2:
     
     SETCURSOR 0019H
 
     MOV BL,COUNTER
     ADD BL,"0"
     
     CMP BL,"9"
     JB SKEP
     MOV BL,"0" 
     SKEP: 
     DISPLAYCHARACTER BL
     MOV BL,COUNTER  
     CMP NPUTIME,BL 
     JNZ MP1
     SETCURSOR 0A00H  
     CHANGECOLOR 0,80D
     SETCURSOR 0A00H
     SHOWMESSAGE MESS11
     ADD NPUTIME,04H  
     MOV PU1CLEARER,BL
     MOV PU2CLEARER,BL
     MOV BX,0
     MOV BL,PUIND
     POWERUPS PUGEN[BX],PUPOS
     INC PUIND 
     JMP MP1
     


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;GAME DONE;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


   
   
   
   
   
   
   
   
   
   
   
                
                
                
                
                
   
   
   
   
   
   
   
   
   



        CHAT:    

;---------------------------------SCREEN INTIALIZATION------------------------ 
       
        MOV CURSORPOS1,0100H
        MOV CURSORPOS2,0E00H   ;SET INTIAL MOUSE LOCATIONS

        CLEARSCREEN            ;CLEARS SCREEN TO REMOVE ALL PREVIOUS PRINTED STUFF
        
        SETCURSOR 0000H        
        SHOWMESSAGE P1NAME     
        SETCURSOR 0D00H
        SHOWMESSAGE P2NAME
        
        SETCURSOR 0C00H
        SHOWMESSAGE BORDER      ;PRINT MIDDLE LINE 
        
        
        
;--------------------------------SERIAL INITIALIZATION----------------
        
         CALL INTIALIZESERIAL
;        
               
   ;ßßßßßßßß+++++++++++SEND++++++++ßßßßßßßßß
        
        
        
        SEN: 
   
        MOV AH,1   
        INT 16H
        JZ REC                  ;RECIEVE INPUT
        
        
        
        CMP AH,01H 
        JZ MAINMENU             ;JMP TO MAIN MENU IF ESC IS PRESSED
        
        
        CMP AH,1CH
        JNZ NOTENTER            
         
        MOV DX,CURSORPOS1       ;IF ENTER KEY IS PRESSED
        CMP DH,0BH              
        JZ ENTERATEND  
        
        MOV DL,0FFH             ;IF CURSOR IS NOT AT THE END OF THE CHAT, MOVE CURSOR TO THE BEGINNING OF THE NEW LINE
        MOV CURSORPOS1,DX
        SETCURSOR CURSORPOS1
        JMP NOTENTER
        
        
        ENTERATEND:  
        
        MOV DX,0A4FH              ;IF ENTER IS PRESSED AT THE END OF THE CHAT, SCROLL AND SET THE CURSOR AT THE BEGINNING OF THE LINE
        MOV CURSORPOS1,DX
        MOV VALUE,AL              ;MOVE THE ASCII OF THE INPUT TO VALUE
        SETCURSOR CURSORPOS1      ;SETS THE CURSOR OF THE UPPER CHAT SENDER
        PUSHA
        mov ah, 06h
        mov al, 1
        mov bh, 07      
        mov cx, 0100h
        mov dx, 0B4Fh 
        int 10h
        POPA 
        
        
        NOTENTER:
        
        
        
         
        
      
         
        MOV VALUE,AL              ;MOVE THE ASCII OF THE INPUT TO VALUE
        
        SETCURSOR CURSORPOS1      ;SETS THE CURSOR OF THE UPPER CHAT SENDER
        
        
        
        MOV DX,CURSORPOS1         ;MOVES THE CURSOR OF THE UPPER CHAT TO DX TO COMPARE LATER ON
        
        CMP DL,079D                ;IF THE CURSOR IS @ THE END OF THE LINE THEN DO THE FOLLOWING ELSE
        JNZ SCROLLUP
        
        CMP CURSORPOS1,0B4FH
        JZ SCROLLUP:
        
        INC DH                    ;INC THE ROWS
        
        MOV DL,0                  ;SETS THE CURSOR TO THE BEGINNING OF THE LINE
        SETCURSOR DX
        
        MOV CURSORPOS1,DX         ;MOVES THE FIXED CURSOR COORDINATES TO THE VARIABLE
        
        
        
        SCROLLUP:  
                
             
        CMP CURSORPOS1,0B4FH       ;IF NOT AT THE END OF THE CHAT, THEN MOVE TO A NEW LINE
        JNZ PRINTTHEUPPER          ;ELSE SCROLL

        PUSHA
        mov ah, 06h
        mov al, 1
        mov bh, 07      
        mov cx, 0100h
        mov dx, 0B4Fh 
        int 10h
        MOV DX,CURSORPOS1
        MOV DL,0
        
        MOV CURSORPOS1,DX 
        SETCURSOR CURSORPOS1
        POPA
        
        
        
        
        PRINTTHEUPPER:   

        
        DISPLAYCHARACTER VALUE ;DISPLAY THE SENDER CHARACTER PRESSED
        CLEARBUFFER
        
        
        
        
        
        
        CMP VALUE,08           ;IF THE KEY PRESSED IS BACKSPACE, PRINT NULL ON THE PREVIOUS POSITION
        JZ  BACKSPACE
        
        ADD CURSORPOS1,0001 
      
        JMP DONEBS
        
        BACKSPACE:
        MOV DX,CURSORPOS1
        CMP DL,00 
        JZ DONEBS
        SUB CURSORPOS1,0001
        DISPLAYCHARACTER 00 
        
        DONEBS:
        
          
       CALL SENDING
       
       
       
        ;ßßßßßßßß+++++++++++RECEIEVE++++++++ßßßßßßßßß
        REC:
        
        
        MOV DX,3FDH 		   ;Line Status Register  	
        IN AL,DX 			   ;Read Line Status
        TEST AL , 1
        JZ SEN 
        MOV DX,03F8H
        IN AL,DX 
        
        MOV VALUE,AL
        
        SETCURSOR CURSORPOS2   
        

        
        CMP VALUE,13D
        JNZ NOTENTER1
         
        MOV DX,CURSORPOS2      ;IF NOT AT THE END OF THE CHAT, THEN MOVE TO A NEW LINE
        CMP DH,18H             ;ELSE SCROLL
        JZ ENTERATEND1
        MOV DL,0FFH
        MOV CURSORPOS2,DX
        SETCURSOR CURSORPOS2
        JMP NOTENTER1
        
        ENTERATEND1:  
        
        MOV DX,0174FH
        MOV CURSORPOS2,DX
        
     
        PUSHA
        mov ah, 06h
        mov al, 1
        mov bh, 07      
        mov cx, 0E00h
        mov dx, 184Fh 
        int 10h
        POPA    
        
        NOTENTER1:

        MOV DX,CURSORPOS2 
        CMP DL,079D
        JNZ SCROLLDOWN
        
          
        CMP CURSORPOS2,184FH
        JZ SCROLLDOWN
        

        INC DH
        MOV DL,0
        SETCURSOR DX
        MOV CURSORPOS2,DX 
        
;-------------------------------------SCROLL THE RECIVER PART--------------------

        SCROLLDOWN:
        
         
        CMP CURSORPOS2,184FH
        JNZ PRINTTHEBOTTOM 
        
        PUSHA
        mov ah, 06h
        mov al, 1
        mov bh, 07      
        mov cx, 0E00h
        mov dx, 184Fh 
        int 10h 
        MOV DX,CURSORPOS2
        MOV DL,0
        
        MOV CURSORPOS2,DX 
        SETCURSOR CURSORPOS2
        POPA
        PRINTTHEBOTTOM:

        
        DISPLAYCHARACTER VALUE
        
        CMP VALUE,08
        JZ  BACKSPACE1
        
        
        ADD CURSORPOS2,0001 
      
        JMP SEN
        
        BACKSPACE1:
        MOV DX,CURSORPOS2
        CMP DL,00H 
        JZ SEN
        SUB CURSORPOS2,0001
        DISPLAYCHARACTER 00 
        
        
         
        JMP SEN   		



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;CHAT DONE;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
HALT:
HLT 
MAIN ENDP 
INTIALIZEAPP PROC  
    
            
;--------------------------------SERIAL INITIALIZATION----------------
        
         CALL INTIALIZESERIAL
        
        
        
           
        CLEARSCREEN

        MOV SI,0
        MOV DI,0
    
;         ßßßßßßßßßPLAYER NAMESßßßßßßß   
         

    
    
        
         
        
        CLEARSCREEN               ;CLEARS SCREEN FOR NEXT OUTPUT
        SETCURSOR 0A15H           ;SETS CURSOR 
        SHOWMESSAGE MESS4         ;PRINT FIRST NAME REQUEST MESSAGE
        SETCURSOR 0B15H           ;SETS CURSOR
        MOV BX,OFFSET P1NAME      ;MOV OFFSET OF FIRST PLAYER NAME VARIABLE
        TAKELETTER                ;MACRO THAT TAKES A LETTER ONLY
        MOV [BX],AL               ;MOV THE LETTER TO THE FIRST PLACE OF THE PLAYER NAME              
        DISPLAYCHARACTER AL       ;DISP
        INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
        MOV CL,13                 ;COUNTER FOR THE LOOP
        TAKENAME1:                ;LOOP TO TAKE THE REST OF THE NAME
        GETKEY                    ;MACRO THAT GETS KEY PRESSED
        CMP AH,1CH                ;CMP WITH 'ENTER' 
        JZ ENDTN1                 ;IF ENTER IS PRESSES END LOOP
        MOV [BX], AL              ;MOVS THE LETTER TO MEMORY
        DISPLAYCHARACTER AL       ;DISPLAY TAKEN LETTER
        INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
        DEC CL                    ;DECREMENT COUNTER
        JNZ TAKENAME1             ;JMPS TO TAKE THE NEXT LETTER
        ENDTN1:                   ;ENDING INPUT LOOP 
        MOV [BX],'$'              ;MOVE AN ENDING CHAR TO THE END OF THE NAME
      
        MOV VALUE,"#"      
        INFCHECK: 
        CLEARSCREEN 
        SETCURSOR 0C20H
        SHOWMESSAGE MESS5
        CALL SENDING
        
        CALL RECEIVING
        
        CMP AL,VALUE
        
        JZ RECIEVED
             
        JMP INFCHECK
  
     

           
       RECIEVED: 
       
       
       
          MOV CL,P1NAME[SI]
          MOV VALUE,CL
        
          CALL SENDING
        
          CALL RECEIVING 
          
          MOV P2NAME[DI],AL
         
       

        INC DI
        INC SI
        CMP DI,14D
        JZ DONE1 
        
        JMP RECIEVED
        
        
        DONE1:
        
       
  
  

 
 
 
RET
INTIALIZEAPP ENDP




 ;-----------------
 ;-----------------
MAINSC PROC
    CLEARBUFFER
    MOV BX,0
    CLEARSCREEN

    TAKEINPUT: 
    SETCURSOR 0A15H   
    SHOWMESSAGE MESS1  
    SETCURSOR 0C15H   
    SHOWMESSAGE MESS2  
    SETCURSOR 0E15H   
    SHOWMESSAGE MESS3  
    READKEY: 
    
            
    GET:GETKEYCHAT
                 
    CMP AH,3CH         
    JNZ SKIP    
    CALL INTIALIZESERIAL
    INFCHECK1: 
    MOV VALUE,3CH  
   
    CALL SENDING 
    CALL RECEIVING
   
    CMP AL,VALUE 
    JZ DONECHAT 

    JMP INFCHECK1
                  
   
    SKIP:
    CMP AH,3DH        
    JNZ  SKIP1 
    MOV VALUE,3DH
        CALL INTIALIZESERIAL
    MOV VALUE,AH  
    
    INFCHECK2: 
     
   
    
    CALL SENDING
    
    CALL RECEIVING
    
    CMP AL,VALUE
    
    JZ DONEGAME
         
    JMP INFCHECK2
           
           
           
    SKIP1:       
                  
    CMP AH,01H        
    JNZ  SKIP2 
    CMP INVITATION,3
    JNZ GET 
    MOV VALUE,01H
    CALL INTIALIZESERIAL
    MOV VALUE,AH  
    
    INFCHECK3: 
     
    SETCURSOR 1700H
    SHOWMESSAGE MESS14
    CALL SENDING
    
    CALL RECEIVING
    
    CMP AL,VALUE
    
    JZ DONEESCAPE
         
    JMP INFCHECK3
    
    
                  
    SKIP2: 
    JMP TAKEINPUT
    
    DONECHAT:
    MOV VALUE,3CH
    CALL SENDING        
    MOV APPMODE,0  
    MOV INVITATION,0
    JMP DONE
    DONEGAME:
    MOV VALUE,3DH
    CALL SENDING
    MOV APPMODE,1 
    MOV INVITATION,0
    JMP DONE
    DONEESCAPE:
    MOV VALUE,01H
    CALL SENDING
    MOV APPMODE,2 
    MOV INVITATION,0
    
    
    
    DONE:
           
RET
MAINSC ENDP    



INTIALIZEGAME PROC 
     CLEARSCREEN    ;CLEARS SCREEN FOR THE GAME BEGINING
     SETCURSOR 0200H  ;SETS CURSOR AT THE SECOND LINE TO PRINT THE UPPER BORDER
     SHOWMESSAGE BORDER ;PRINTS THE DASH ONCE
     SETCURSOR 1600H
     SHOWMESSAGE BORDER   
      SETCURSOR 1300H
     SHOWMESSAGE BORDER 
;-----------------------------------------------PRINT STATUS BARS-------------     
     SETCURSOR 0100H   ;SET THE CURSOR AT THE TOP PART OF THE SCREEN TO START DRAWING    
     SHOWMESSAGE P2NAME  ;SHOW THE SECOND PLAYER NAME
     SETCURSOR 0000H
     CHANGECOLOR 0CH,20D
     SHOWMESSAGE HEALTH
     SETCURSOR 1500H    ;SET THE CURSOR AT THE BOTTOM PART OF THE SCREEN TO START DRAWING
     SHOWMESSAGE P1NAME
     SETCURSOR 1400H
     CHANGECOLOR 0CH,20D
     SHOWMESSAGE HEALTH    ;SHOW THE FIRST PLAYER NAME  
     SETCURSOR 1800H   ;SET THE CURSOR AT THE TOP PART OF THE SCREEN TO START DRAWING    
     SHOWMESSAGE P2NAME  ;SHOW THE SECOND PLAYER NAME  
      SHOWMESSAGE MESS12
     MOV AH,3
     MOV BH,0
     INT 10H
     MOV CHATCURSORREC,DX 
     MOV BEGINCHATREC ,DX 
     SETCURSOR 1700H   ;SET THE CURSOR AT THE TOP PART OF THE SCREEN TO START DRAWING    
     SHOWMESSAGE P1NAME  ;SHOW THE SECOND PLAYER NAME 
      SHOWMESSAGE MESS12
     MOV AH,3
     MOV BH,0
     INT 10H
     MOV CHATCURSORSEN,DX 
     MOV BEGINCHATSEN ,DX
;----------------------DRAWS PLAYERS AT THEIR CURRENT LOCATION--------------------------------
     CALL DRAWPLAYERONE
     CALL DRAWPLAYERTWO
RET
INTIALIZEGAME ENDP 
;--------------------------- 
SENDING PROC
       
        MOV DX,3FDH
        SENDER:	   	
        IN AL,DX 			   ;Read Line Status
        TEST al , 00100000b
        JZ SENDER
        MOV DX,3F8H                 ; Transmit data register	  
        MOV AL,VALUE
        OUT DX,AL

RET 
SENDING ENDP 
;--------------------------------  

INTIALIZESERIAL PROC
        MOV DX,3FBH 		    ;LINE CONTROL REGISTER
        MOV AL,10000000B		;SET DIVISOR LATCH ACEESS BIT
        OUT DX,AL				;OUT IT 
        MOV DX,3F8H			    
        MOV AL,0CH			
        OUT DX,AL
        MOV DX,3F9H
        MOV AL,00H
        OUT DX,AL
        MOV DX,3FBH
        MOV AL,00011011B
        OUT DX,AL
               

RET 
INTIALIZESERIAL ENDP 







;---------------------------------
RECEIVING PROC
       
        RECIEVER:  
        MOV DX,3FDH 		   ;Line Status Register  	
        IN AL,DX 			   ;Read Line Status
        TEST AL , 1
        JZ RECIEVER 
        MOV DX,03F8H
        IN AL,DX 
       

RET 
RECEIVING ENDP


RECEIVINGCHAT PROC
       
        RECIEVER1:  
        MOV DX,3FDH 		   ;Line Status Register  	
        IN AL,DX 			   ;Read Line Status
        TEST AL , 1
        JZ NOTF2 
        MOV DX,03F8H
        IN AL,DX   
        CMP AL,3CH
        JNZ ANOTHER
        SETCURSOR 1700H
         SHOWMESSAGE MESS13 
         MOV INVITATION ,1
         JMP NOTF2
       ANOTHER: CMP AL,3DH
        JNZ ANOTHER1
        SETCURSOR 1700H
         SHOWMESSAGE MESS14 
         MOV INVITATION ,2
         JMP NOTF2  
        ANOTHER1: CMP AL,01H
        JNZ NOTF2
         MOV INVITATION ,3
         
     
       
NOTF2:       
       

RET 
RECEIVINGCHAT ENDP  
    


DRAWPLAYERONE PROC 
 		  PUSH P1POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,5
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
;------------DRAW MIDDLE CANNON-------		  
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 0CH,1
		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW RIGHT CANNON----
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER PSHAPE
		  ADD P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW LEFT CANNON----
		  SUB P1POS,0004H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER PSHAPE
		  SUB P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER PSHAPE
          POPA
		  POP P1POS 		
RET
DRAWPLAYERONE ENDP 
;-----------------------
DRAWPLAYERTWO PROC 
          PUSH P2POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,5
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
;------------DRAW MIDDLE CANNON-------		  
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 0EH,1
		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW RIGHT CANNON----
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER PSHAPE
		  SUB P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW LEFT CANNON----
		  SUB P2POS,0004H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER PSHAPE
		  ADD P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER PSHAPE
          POPA
		  POP P2POS     
RET
DRAWPLAYERTWO ENDP	
;------------------------
DELETEPLAYERONE PROC 
 		  PUSH P1POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,5
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
;------------DRAW MIDDLE CANNON-------		  
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 0CH,1
		  DISPLAYCHARACTER 00
;------------------------DRAW RIGHT CANNON----
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER 0
		  ADD P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER 0
;------------------------DRAW LEFT CANNON----
		  SUB P1POS,0004H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER 00
		  SUB P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER 0
          POPA
		  POP P1POS 		  
RET
DELETEPLAYERONE ENDP 
 ;------------------------------
DELETEPLAYERTWO PROC 
          PUSH P2POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,5
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
;------------DRAW MIDDLE CANNON-------		  
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 0EH,1
		  DISPLAYCHARACTER 0
;------------------------DRAW RIGHT CANNON----
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER 0
		  SUB P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER 0
;------------------------DRAW LEFT CANNON----
		  SUB P2POS,0004H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER 0
		  ADD P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER 0
          POPA
		  POP P2POS 		      
RET
DELETEPLAYERTWO ENDP	
;----------------------		  
MOVEPLAYERONE PROC
PUSHA    
CMP DIRECTION,"L"
JZ LEFT1
CMP DIRECTION,"R"
JZ RIGHT1
JMP HALT1
LEFT1:
CALL DELETEPLAYERONE
SUB P1POS,0001H
CALL DRAWPLAYERONE
JMP HALT1
RIGHT1:
CALL DELETEPLAYERONE
ADD P1POS,0001H
CALL DRAWPLAYERONE
HALT1:
POPA   
RET 
MOVEPLAYERONE ENDP
 ;--------------------------
MOVEPLAYERTWO PROC
PUSHA    
CMP DIRECTION,"L"
JZ LEFT
CMP DIRECTION,"R"
JZ RIGHT
JMP HALT2
LEFT:
CALL DELETEPLAYERTWO
SUB P2POS,0001H
CALL DRAWPLAYERTWO
JMP HALT2
RIGHT:
CALL DELETEPLAYERTWO
ADD P2POS,0001H
CALL DRAWPLAYERTWO
HALT2:
POPA   
RET 
MOVEPLAYERTWO ENDP  
;----------------------------------------
DRAWBULLETONE PROC
   CMP PU1,04H
   JZ HALT3
   CMP PU1,03H
   JZ HLTPU2 
   CMP P1COUNT,0AH
   JZ HALT3
   PUSHA
    MOV BX,0
    MOV BL,P1COUNT
	MOV DX,P1POS
	MOV P1BPOS[BX],DX
	SUB P1BPOS[BX],0300H
    ADD P1BPOS[BX],0002H
	SETCURSOR P1BPOS[BX]
	CHANGECOLOR 0CH,1
    SETCURSOR P1BPOS[BX]
	DISPLAYCHARACTER 0DBH
	INC P1COUNT
	INC P1COUNT
	POPA 
	JMP HALT3
	HLTPU2:
	MOV PU1,04H	
HALT3:	
RET
DRAWBULLETONE ENDP	
;-------------------------
DRAWBULLETTWO PROC
   CMP PU2,04H
   JZ HALT4
   CMP PU2,03H
   JZ HLTPU1
   CMP P2COUNT,0AH
   JZ HALT4
   PUSHA
    MOV BX,0
    MOV BL,P2COUNT
	MOV DX,P2POS
	MOV P2BPOS[BX],DX
	ADD P2BPOS[BX],0300H
    ADD P2BPOS[BX],0002H
	SETCURSOR P2BPOS[BX]
	CHANGECOLOR 0EH,1
    SETCURSOR P2BPOS[BX]
	DISPLAYCHARACTER 0DBH
	INC P2COUNT
	INC P2COUNT
	POPA
	JMP HALT4
	HLTPU1:
	MOV PU2,04H	
HALT4:	
RET
DRAWBULLETTWO ENDP	
;--------------------------	    
UPDATEBULLETONE PROC 
    
PUSHA
CMP PU1,04H
JZ DRAWWAVE1
CMP P1COUNT,00
JZ HALT5
MOV BX,0
MOV SI,BX
MOV BL,P1COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1
MAINLOOP:
PUSH CX
MOV BX,0
MOV BL,P1COUNT
SHR BX,1
;DRAWAMMO 174BH,BX
MOV DX,P1BPOS[SI]
PUSHA
MOV CX, BARRIERLOCATION
ADD CX, 0100H


CMP P1BPOS[SI], CX ;FIRST BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX   ;SECOND BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX    ;THIRD BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX     ;FOURTH BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX        ;FIFTH BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX       ;SIXTH BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX      ;SEVENTH BIT
JZ REBOUND

ADD CX, 0001H
CMP P1BPOS[SI], CX        ;EIGTH BIT
JZ REBOUND


ADD CX, 0001H
CMP P1BPOS[SI], CX        ;NINTH BIT
JZ REBOUND

JMP KAMELSCODE

REBOUND:  
;MOV P1BPOS[SI],0000H
MOV BL, RP1COUNT
MOV BH, 00H
MOV CX,P1BPOS[SI]

MOV RP1BARR[BX], CX

MOV CX,P1BPOS[DI]
MOV P1BPOS[SI],CX
SUB P1COUNT,02H

ADD RP1COUNT, 02H

SUB DI,02H
SUB SI,02H

CALL CLEARSCREENSTRIP
CALL DRAWREBOUND1  
KAMELSCODE:
POPA
CMP DX,PUPOS
JNZ SKIPA 
PUSHA
MOV BL,COUNTER  
MOV PU1CLEARER,BL
ADD PU1CLEARER,02
MOV PUPOS,0000H
MOV BX,0
MOV BL,PUIND
MOV AL,PUGEN[BX]
MOV PU1,AL
POPA
SKIPA:
CMP DH,004H
JB REACHED
SETCURSOR P1BPOS[SI]
DISPLAYCHARACTER 00H
SUB P1BPOS[SI],0100H
SETCURSOR P1BPOS[SI]
CHANGECOLOR 0CH,1
DISPLAYCHARACTER 0DBH
JMP HALT6
REACHED:
SETCURSOR P1BPOS[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,P1BPOS[SI]
MOV BX,P2POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DX,BX
JZ POPBACK
INC BL
CMP DX,BX
JZ POPBACK
INC BL
CMP DX,BX
JZ POPBACK
INC BL
CMP DX,BX
JZ POPBACK
INC BL
CMP DX,BX
JZ POPBACK
JMP GOON
POPBACK:
DEC P2HEALTH
GOON:
MOV BX,P1BPOS[DI]
MOV P1BPOS[SI],BX
SUB P1COUNT,02H
SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,P1COUNT
SHR BX,1
;DRAWAMMO 174BH,BX
HALT6:
PUSH DX
MOV DX, 0
MOV DL, P2HEALTH
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ MAINLOOP

JMP HALT5

DRAWWAVE1:
PUSHA
SETCURSOR P1WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P1WAVEPOS
SHOWMESSAGE MESS10 
SUB P1WAVEPOS,0100H
SETCURSOR P1WAVEPOS 
CHANGECOLOR 0CH,80D 
SETCURSOR P1WAVEPOS 
SHOWMESSAGE MESS10 
POPA
CMP P1WAVEPOS,0300H
JNZ HALT5 
SETCURSOR P1WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P1WAVEPOS
SHOWMESSAGE MESS10 
MOV P1WAVEPOS,1200H
MOV PU1,0
DEC P2HEALTH  

CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT5:
POPA       
RET
UPDATEBULLETONE ENDP 
;--------------
UPDATEBULLETTWO  PROC
PUSHA     
CMP PU2,04H
JZ DRAWWAVE2
CMP P2COUNT,00
JZ HALT7
MOV BX,0
MOV SI,BX
MOV BL,P2COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1
MAINLOOP1:
PUSH CX
MOV BX,0
MOV BL,P2COUNT
SHR BX,1
;DRAWAMMO 004BH,BX
MOV DX,P2BPOS[SI]
PUSHA
MOV CX, BARRIERLOCATION
SUB CX, 0100H


CMP P2BPOS[SI], CX ;FIRST BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX   ;SECOND BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX    ;THIRD BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX     ;FOURTH BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX        ;FIFTH BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX       ;SIXTH BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX      ;SEVENTH BIT
JZ REBOUND2

ADD CX, 0001H
CMP P2BPOS[SI], CX        ;EIGTH BIT
JZ REBOUND2


ADD CX, 0001H
CMP P2BPOS[SI], CX        ;NINTH BIT
JZ REBOUND2

JMP KAMELSCODE2

REBOUND2:  
;MOV P1BPOS[SI],0000H
MOV BL, RP2COUNT
MOV BH, 00H
MOV CX,P2BPOS[SI]

MOV RP2BARR[BX], CX

MOV CX,P2BPOS[DI]
MOV P2BPOS[SI],CX
SUB P2COUNT,02H

ADD RP2COUNT, 02H

SUB DI,02H
SUB SI,02H

;CALL CLEARSCREENSTRIP
CALL DRAWREBOUND2  
KAMELSCODE2:
POPA

CMP DX,PUPOS
JNZ SKIPB 
PUSHA     
MOV BL,COUNTER  
MOV PU2CLEARER,BL
ADD PU2CLEARER,02
MOV PUPOS,0000H
MOV BX,0
MOV BL,PUIND
MOV AL,PUGEN[BX]
MOV PU2,AL
POPA
SKIPB:
CMP DH,011H
JA REACHED1
SETCURSOR P2BPOS[SI]
DISPLAYCHARACTER 00H
ADD P2BPOS[SI],0100H
SETCURSOR P2BPOS[SI]
CHANGECOLOR 0EH,1
DISPLAYCHARACTER 0DBH     
JMP HALT8
REACHED1:
SETCURSOR P2BPOS[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,P2BPOS[SI]
MOV BX,P1POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DX,BX
JZ POPBACK1
INC BL
CMP DX,BX
JZ POPBACK1
INC BL
CMP DX,BX
JZ POPBACK1
INC BL
CMP DX,BX
JZ POPBACK1
INC BL
CMP DX,BX
JZ POPBACK1
JMP GOON1
POPBACK1:
DEC P1HEALTH

GOON1:


MOV BX,P2BPOS[DI]
MOV P2BPOS[SI],BX
SUB P2COUNT,02H

SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,P2COUNT
SHR BX,1
;DRAWAMMO 004BH,BX




 
 

HALT8:
PUSH DX
MOV DX, 0
MOV DL, P1HEALTH
ADD DH, 14H
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ MAINLOOP1
JMP HALT7
DRAWWAVE2:
PUSHA
SETCURSOR P2WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P2WAVEPOS
SHOWMESSAGE MESS10 
ADD P2WAVEPOS,0100H
SETCURSOR P2WAVEPOS 
CHANGECOLOR 0EH,80D 
SETCURSOR P2WAVEPOS 
SHOWMESSAGE MESS10 
POPA
CMP P2WAVEPOS,1500H
JNZ HALT7 
SETCURSOR P2WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P2WAVEPOS
SHOWMESSAGE MESS10 
MOV P2WAVEPOS,0500H
MOV PU2,0
DEC P1HEALTH  

CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT7:
POPA

RET
UPDATEBULLETTWO ENDP   

     
DRAWBARRIERS    PROC
    PUSHA
    MOV BX, 0009H
    MOV CX, BARRIERLOCATION
    LOOP1:
    
    SETCURSOR BARRIERLOCATION
    PRINTCOLOR 0CH, 0DBH
    ADD BARRIERLOCATION, 0001H
    DEC BX
    JNZ LOOP1   
    MOV BARRIERLOCATION, CX
    POPA
    ret
    DRAWBARRIERS ENDP
    
MOVEBARRIERS    PROC    
    PUSHA
    MOV CX, BARRIERLOCATION
    ADD CX, 0009H

    CMP CX, 0B50H
    JGE MOVELEFT
    
    
    
    MOV CX, BARRIERLOCATION
    SUB CX, 0001H
    CMP CX, 0B00H
    JLE MOVERIGHT 
    CMP BARRIERLEFT, 01H
    JZ MOVELEFT
    
    MOV CX, BARRIERLOCATION
    SUB CX, 0009H
    CMP CX, 0000H
    JLE MOVERIGHT
    
    
    MOVERIGHT:
    
    MOV BARRIERLEFT, 00H
    MOV CX, BARRIERLOCATION
    ADD CX, 000AH
    PRINTCOLOR 0CH, 0DBH
    ADD BARRIERLOCATION, 0001H
    
    MOV CX, BARRIERLOCATION
    SUB CX, 0002H
    SETCURSOR CX
    DISPLAYCHARACTER 00H
    JMP HALTER
    
    
    MOVELEFT:
    MOV BARRIERLEFT, 01H
    MOV CX, BARRIERLOCATION
    ADD CX, 0009H
    DISPLAYCHARACTER 00H
    SUB BARRIERLOCATION, 0001H
    MOV CX, BARRIERLOCATION
    SUB CX, 0001H
    SETCURSOR CX
    PRINTCOLOR 0CH, 0DBH
    
    HALTER:
    POPA
    ret
    MOVEBARRIERS ENDP 
   
CLEARSCREENSTRIP	PROC

PUSHA
MOV BL, 50H
MOV CX, 0C00H

STRIP:
CMP CX, 0C50H
JZ ENOUGH
SETCURSOR CX
DISPLAYCHARACTER 00H
ADD CX, 0001H
DEC BL
CMP BL, 00H
JNZ STRIP
ENOUGH:
POPA 
RET
CLEARSCREENSTRIP ENDP 

REBOUNDBULLETONE PROC
PUSHA     

CMP RP1COUNT,00
JZ HALT17
MOV BX,0
MOV SI,BX
MOV BL,RP1COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1

REBOUND1MAINLOOP1:
PUSH CX
MOV BX,0
MOV BL,RP1COUNT
SHR BX,1
;DRAWAMMO 004BH,BX
MOV DX,RP1BARR[SI]


CMP DH,011H
JA REBOUND1REACHED1

SETCURSOR RP1BARR[SI]
DISPLAYCHARACTER 00H

ADD RP1BARR[SI],0100H
SETCURSOR RP1BARR[SI]
CHANGECOLOR 0EH,1

DISPLAYCHARACTER 0DBH     

JMP HALT18

REBOUND1REACHED1:
SETCURSOR RP1BARR[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,RP1BARR[SI]
MOV BX,P1POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DX,BX
JZ REBOUND1POPBACK1

INC BL
CMP DX,BX
JZ REBOUND1POPBACK1

INC BL
CMP DX,BX
JZ REBOUND1POPBACK1

INC BL
CMP DX,BX
JZ REBOUND1POPBACK1

INC BL
CMP DX,BX
JZ REBOUND1POPBACK1

JMP REBOUND1GOON1

REBOUND1POPBACK1:
DEC P1HEALTH

REBOUND1GOON1:


MOV BX,RP1BARR[DI]
MOV RP1BARR[SI],BX
SUB RP1COUNT,02H

SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,RP1COUNT
SHR BX,1
;DRAWAMMO 004BH,BX




 
 

HALT18:
PUSH DX
MOV DX, 0
MOV DL, P1HEALTH
ADD DH, 14H
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ REBOUND1MAINLOOP1
JMP HALT17
CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT17:
POPA

RET
REBOUNDBULLETONE ENDP















DRAWREBOUND1 PROC

   PUSHA
    MOV BX,0
    MOV BL,RP1COUNT
	MOV DX,P1POS
	MOV RP1BARR[BX],DX
	ADD RP1BARR[BX],0300H
    ADD RP1BARR[BX],0002H
	SETCURSOR RP1BARR[BX]
	CHANGECOLOR 0EH,1
    SETCURSOR RP1BARR[BX]
	DISPLAYCHARACTER 0DBH
	INC RP1COUNT
	INC RP1COUNT
	POPA

RET
DRAWREBOUND1 ENDP 


DRAWREBOUND2 PROC
   PUSHA
    MOV BX,0
    MOV BL,RP2COUNT
	MOV DX,P2POS
	MOV RP2BARR[BX],DX
	SUB RP2BARR[BX],0300H
    ADD RP2BARR[BX],0002H
	SETCURSOR RP2BARR[BX]
	CHANGECOLOR 0CH,1
    SETCURSOR RP2BARR[BX]
	DISPLAYCHARACTER 0DBH
	INC RP2COUNT
	INC RP2COUNT
	POPA   
    
DRAWREBOUND2 ENDP   







REBOUNDBULLETTWO    PROC
    PUSHA

CMP RP2COUNT,00
JZ HALT25
MOV BX,0
MOV SI,BX
MOV BL,RP2COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1
REBOUND2MAINLOOP:
PUSH CX
MOV BX,0
MOV BL,RP2COUNT
SHR BX,1
;DRAWAMMO 174BH,BX
MOV DX,RP2BARR[SI]
CMP DX,PUPOS
JNZ REBOUND2SKIPA 

REBOUND2SKIPA:
CMP DH,004H
JB REBOUND2REACHED
SETCURSOR RP2BARR[SI]
DISPLAYCHARACTER 00H
SUB RP2BARR[SI],0100H
SETCURSOR RP2BARR[SI]
CHANGECOLOR 0CH,1
DISPLAYCHARACTER 0DBH
JMP HALT26
REBOUND2REACHED:
SETCURSOR RP2BARR[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,RP2BARR[SI]
MOV BX,P2POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DX,BX
JZ REBOUND2POPBACK
INC BL
CMP DX,BX
JZ REBOUND2POPBACK
INC BL
CMP DX,BX
JZ REBOUND2POPBACK
INC BL
CMP DX,BX
JZ REBOUND2POPBACK
INC BL
CMP DX,BX
JZ REBOUND2POPBACK
JMP REBOUND2GOON
REBOUND2POPBACK:
DEC P2HEALTH

REBOUND2GOON:

MOV BX,RP2BARR[DI]
MOV RP2BARR[SI],BX
SUB RP2COUNT,02H
SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,RP2COUNT
SHR BX,1
;DRAWAMMO 174BH,BX
HALT26:
PUSH DX
MOV DX, 0
MOV DL, P2HEALTH
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ REBOUND2MAINLOOP

JMP HALT25



CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT25:
POPA       
RET
REBOUNDBULLETTWO ENDP
END MAIN  











